### ISSUE TITLE
最新版本上传的仍然是1.0.0

### ISSUE THREAD

**Issue by Allionc** [tehcneko/MiFitHook#1]
release版本号没变，更新5.0.2也没有生效

**Comment by jw8013** [comment]
想自己编译，结果一直错误:joy:

**Comment by Allionc** [comment]
> 想自己编译，结果一直错误😂

那看来只能等play更新版本大佬再上线的时候看一下了

**Comment by jw8013** [comment]
> > 想自己编译，结果一直错误😂
> 
> 那看来只能等play更新版本大佬再上线的时候看一下了

编译成功了
https://wwa.lanzoui.com/b010go2dc  提取码：gl73

**Comment by Allionc** [comment]
> > > 想自己编译，结果一直错误😂
> > 
> > 
> > 那看来只能等play更新版本大佬再上线的时候看一下了
> 
> 编译成功了，签名是自己的，所以没核心破解的话，需要卸载后再安装
> https://wwa.lanzoui.com/b010go2dc 提取码：gl73

可以用了，牛的👍🏻

**Comment by tehcneko** [comment]
弄好了
